# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-03 22:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname1', models.CharField(max_length=255)),
                ('nickname2', models.CharField(max_length=255)),
                ('lastMessage', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('msg', models.CharField(max_length=255)),
                ('from_nickname', models.CharField(max_length=255)),
                ('to_nickname', models.CharField(max_length=255)),
                ('dateTimeSent', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messageService.Chat')),
            ],
        ),
    ]
