# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-03 23:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messageService', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='chat',
            table='Chats',
        ),
        migrations.AlterModelTable(
            name='message',
            table='Messages',
        ),
    ]
